log:
  level: debug

interval: 3
max: 100
templates: ./templates

watch:
  type: etcdv3
  config:
    endpoints:
      - 127.0.0.1:2379
  prefixes:
    - /traefik

processors:
  - src: traefik.com.conf.tpl
    dst: /tmp/traefik.com.yml
    prefixes:
      - /traefik/http
  - src: nginx.traefik.com.conf.tpl
    dst: /tmp/nginx.treafik.com.conf
    prefixes:
      - /traefik/http